// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scriptura.Infrastructure.Postgres;

#nullable disable

namespace Scriptura.Infrastructure.Migrations
{
    [DbContext(typeof(ScripturaDbContext))]
    [Migration("20260413203406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scriptura.Domain.Entities.Catalog.ArchivalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.PrimitiveCollection<List<Guid>>("_settlementIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("settlement_ids");

                    b.HasKey("Id");

                    b.ToTable("archival_items", (string)null);
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Catalog.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.PrimitiveCollection<List<string>>("_alternativeNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alternative_names");

                    b.HasKey("Id");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Digitization.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArchivalItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("archival_item_id");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.HasIndex("ArchivalItemId");

                    b.ToTable("scans", (string)null);
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Catalog.ArchivalItem", b =>
                {
                    b.OwnsOne("Scriptura.Domain.ValueObjects.ArchivalSignature", "Signature", b1 =>
                        {
                            b1.Property<Guid>("ArchivalItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ArchiveCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("archive_code");

                            b1.Property<string>("Fond")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("fond");

                            b1.Property<string>("Inventory")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("inventory");

                            b1.Property<string>("ItemNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("item_number");

                            b1.HasKey("ArchivalItemId");

                            b1.HasIndex("ArchiveCode", "Fond", "Inventory", "ItemNumber")
                                .IsUnique();

                            b1.ToTable("archival_items");

                            b1.WithOwner()
                                .HasForeignKey("ArchivalItemId");
                        });

                    b.OwnsOne("Scriptura.Domain.ValueObjects.DateRange", "CoveredYears", b1 =>
                        {
                            b1.Property<Guid>("ArchivalItemId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("end_year");

                            b1.Property<int?>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("start_year");

                            b1.HasKey("ArchivalItemId");

                            b1.ToTable("archival_items");

                            b1.WithOwner()
                                .HasForeignKey("ArchivalItemId");
                        });

                    b.Navigation("CoveredYears");

                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Catalog.Settlement", b =>
                {
                    b.OwnsOne("Scriptura.Domain.ValueObjects.Coordinate", "Location", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("SettlementId");

                            b1.ToTable("settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.OwnsMany("Scriptura.Domain.ValueObjects.HistoricalDivision", "HistoricalDivisions", b1 =>
                        {
                            b1.Property<Guid>("SettlementId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("County")
                                .HasJsonPropertyName("county");

                            b1.Property<string>("Governorate")
                                .HasJsonPropertyName("governorate");

                            b1.Property<string>("Parish")
                                .HasJsonPropertyName("parish");

                            b1.HasKey("SettlementId", "__synthesizedOrdinal");

                            b1.ToTable("settlements", (string)null);

                            b1
                                .ToJson("historical_divisions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.OwnsOne("Scriptura.Domain.ValueObjects.ModernDivision", "ModernAdminDivision", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Community")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("modern_community");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("modern_district");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("modern_region");

                            b1.HasKey("SettlementId");

                            b1.ToTable("settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("HistoricalDivisions");

                    b.Navigation("Location");

                    b.Navigation("ModernAdminDivision");
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Digitization.Scan", b =>
                {
                    b.HasOne("Scriptura.Domain.Entities.Catalog.ArchivalItem", null)
                        .WithMany("Scans")
                        .HasForeignKey("ArchivalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptura.Domain.Entities.Catalog.ArchivalItem", b =>
                {
                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
